fesch/Structorizer.Desktop

- src/lu/fisch/structorizer/elements/Case.java
- src/lu/fisch/structorizer/elements/Forever.java
- src/lu/fisch/structorizer/elements/Repeat.java
- src/lu/fisch/structorizer/elements/While.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/executor/Function.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/parsers/NSDParser.java
Among them issue #17 is fixed (legacy bug).
Furthermore some faults just inserted are fixed now:
1. Function detection had become defective (by an optimisation effort) such that some Turtleizer instructions didn't work anymore.
2. The div operator wasn't recognised anymore.
3. The execution status highlighting wasn't unset on certain loop types after execution ended.
4. changelog.txt failed to reflect the most recent modifications and enhancements,
> Several important bugfixes (some of them concerning own code rebuilding defects).

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/gui/de.txt
In addition, version number in Element.java cleansed (3.22-31dev -> 3.33-31)
I have to apologize that I found this bug somewhat too late.
> Ultimate fix for CASE execution (wrong comparison operator remained)

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/generators/CPlusPlusGenerator.java
Also:
1. Method Executor.stepInstruction() further decomposed
2. changelog.txt and version number prepared for next release
> Bugfixes #21, #24, #25

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/changelog.txt
operator highlighting fixed and string literal colouring added
> changelog changes propagated

- src/lu/fisch/structorizer/elements/Alternative.java
- src/lu/fisch/structorizer/elements/Call.java
- src/lu/fisch/structorizer/elements/Case.java
- src/lu/fisch/structorizer/elements/For.java
- src/lu/fisch/structorizer/elements/Forever.java
- src/lu/fisch/structorizer/elements/Instruction.java
- src/lu/fisch/structorizer/elements/Jump.java
- src/lu/fisch/structorizer/elements/Parallel.java
- src/lu/fisch/structorizer/elements/Repeat.java
- src/lu/fisch/structorizer/elements/Root.java
- src/lu/fisch/structorizer/elements/While.java
- src/lu/fisch/structorizer/gui/Mainform.java
The changes to adopt her contain will fix #28, #31, and #32 and should allow a new release.
Will only have to check whether the changelog.txt update might be missing again...
> Fixes #28, #31, #32

- src/lu/fisch/structorizer/arranger/Arranger.java
- src/lu/fisch/structorizer/arranger/Surface.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/changelog.txt
If there are no new emergency issues, then I'd say this is enough now to roll out a flaw-reduced version.
> Final additions for prepared bugfix release (3.22-32)

- src/lu/fisch/graphics/Rect.java
- src/lu/fisch/structorizer/elements/Alternative.java
- src/lu/fisch/structorizer/elements/Call.java
- src/lu/fisch/structorizer/elements/Case.java
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/elements/For.java
- src/lu/fisch/structorizer/elements/Forever.java
- src/lu/fisch/structorizer/elements/ILoop.java
- src/lu/fisch/structorizer/elements/Instruction.java
- src/lu/fisch/structorizer/elements/Jump.java
- src/lu/fisch/structorizer/elements/Parallel.java
- src/lu/fisch/structorizer/elements/Repeat.java
- src/lu/fisch/structorizer/elements/Root.java
- src/lu/fisch/structorizer/elements/While.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/InputBoxFor.java
- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/utils/StringList.java
Please test bugfixes and publish if okay
> Bugfix3.22

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/executor/DelayableDiagramController.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/turtle/TurtleBox.java
The bugfixes #48 and #49 seem to work now.
I continued the changelog as is but there is a little inconsistency: There are two headlines "Version 3.22"
> Bugfixes #48 and #49 for release 3.23

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/elements/Root.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/generators/CPlusPlusGenerator.java
- src/lu/fisch/structorizer/generators/JavaGenerator.java
- src/lu/fisch/structorizer/generators/PerlGenerator.java
- src/lu/fisch/structorizer/generators/PythonGenerator.java
- src/lu/fisch/structorizer/gui/changelog.txt
Enh. #36 - allowing to pause from input and output dialogs
Enh. #54 - Output instruction with expression list (executor, most generators)
Bugfix #55 - highlighting of variables with keywords as substring mended
Bugfix #57 - Risk of endless loops and other flaws on Perl export
> Four bugfixes and enhancements (-> version 3.23-04)

- build.xml
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/changelog.txt
Accidently disabled Pascal operators reactivated;
Highlighting of jump keywords.
I guess this was definitely my last coding activity before Christmas.
So, I wish you (all) a merry Christmas (without Structorizer ... ;-)
> Bugfix #74, Enhancement #75, Ant Build file

- README.md
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/generators/XmlGenerator.java
- src/lu/fisch/structorizer/gui/changelog.txt
Bugfix #82 and slight modification of README.md, prepared for version 3.23-08
> Bugfix3.23 - includes fix #82

- src/lu/fisch/structorizer/elements/Alternative.java
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/changelog.txt
Version 3.23-16 prepared (just this fix)
> Bugfix #122 (Selection bug in alternatives with option enlargeFALSE)

- src/lu/fisch/structorizer/arranger/Arranger.java
- src/lu/fisch/structorizer/arranger/Diagram.java
- src/lu/fisch/structorizer/arranger/Surface.java
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/changelog.txt
> Bugfix3.23 - Release 3.24 candidate

- src/lu/fisch/structorizer/io/Ini.java
> Update Ini.java (for pending version 3.24-10)

- src/lu/fisch/structorizer/gui/Editor.java
- src/lu/fisch/structorizer/gui/IconLoader.java
- src/lu/fisch/structorizer/gui/InputBox.java
- src/lu/fisch/structorizer/gui/LangDialog.java
- src/lu/fisch/structorizer/gui/Menu.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/locales/Locale.java
- src/lu/fisch/structorizer/locales/Tab.java
- src/lu/fisch/structorizer/locales/Translator.java
- src/lu/fisch/structorizer/locales/TranslatorTableModel.java
- src/lu/fisch/structorizer/locales/de.txt
- src/lu/fisch/structorizer/locales/en.txt
- src/lu/fisch/structorizer/locales/es.txt
As explained under issue #220, there is still some trouble at hand. So this NOT a new release proposal!
> Bugfix3.24 - solution elements for #220 and implementation of #222

- src/lu/fisch/structorizer/elements/Root.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/locales/Locales.java
- src/lu/fisch/structorizer/locales/Translator.java
- src/lu/fisch/structorizer/locales/es.txt
The promised fixes for Translator (+ some code cleanup)
> Bugfix3.24 Release candidate 3.25

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/parsers/D7Parser.java
> Bugfix3.25 - version 3.25-06 candidate

- src/lu/fisch/structorizer/generators/CPlusPlusGenerator.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/locales/de.txt
- src/lu/fisch/structorizer/locales/en.txt
- src/lu/fisch/structorizer/locales/es.txt
- src/lu/fisch/structorizer/locales/it.txt
Perhaps you might wait a little with the roll-out (say till tomorrow morning) in the hope that issue #284 will clarify in the meantime.
> 3.25-06 update: Message translations for #270 revised (EN,DE,ES,IT), C++ export fix.

- src/Structorizer.java
- src/lu/fisch/structorizer/elements/Case.java
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/elements/Subqueue.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/generators/CGenerator.java
- src/lu/fisch/structorizer/generators/Generator.java
- src/lu/fisch/structorizer/generators/PHPGenerator.java
- src/lu/fisch/structorizer/generators/PerlGenerator.java
- src/lu/fisch/structorizer/generators/PythonGenerator.java
- src/lu/fisch/structorizer/gui/About.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/Menu.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/io/Ini.java
- src/lu/fisch/structorizer/locales/de.txt
- src/lu/fisch/structorizer/locales/en.txt
- src/lu/fisch/structorizer/locales/es.txt
- src/lu/fisch/turtle/TurtleBox.java
- Issue #294: Test coverage rules for CASE elements w/o default branch refined
- Enh. #300: New option for online update retrieval and version notification
- Bugfix #301: Parentheses handling around conditions on code export fixed
- Enh. #302: New Turtleizer procedures setPenColor, setBackground
- Bugfix #302: Effects of previous penUp and hideTurtle now undone on new start
> Bugfix3.25 - version 3.25-09 candidate

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/executor/IRoutinePool.java
- src/lu/fisch/structorizer/executor/IRoutinePoolListener.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/parsers/D7Parser.java
Second attempt to instigate the new release
> Fixes #327, adds missing classes

- src/lu/fisch/structorizer/parsers/COBOLParser.java
Minor fixes
* createPicStringFromValues:
* correct length for string values ("\u" must be removed, size / 2) and signed integers
* PIC N for obviously national literals (not starting at "\u00")
* CobVar (constructor for constants): set usage from calculated picture
> COBOLParser:

- src/lu/fisch/structorizer/parsers/COBOLParser.java
* importSearch fixed #493:
* fixed NullPointerException when variables are unknown (for example only partial source parsed)
* fixed PROD_SEARCH_VARYING_VARYING to increment an *additional* index/number
* PROD_START_STATEMENT_START - added with TODO not-supported
* PROD_EXIT_BODY_PERFORM_CYCLE: include as not-supported "continue" JUMP (see #64) as it can be better understand by non-COBOL programmers (and *may* even work with some exports)
> COBOLParser changes

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/gui/changelog.txt
> Bugfix #501 (Creation / editing of CASE and PARALLEL)

- Arranger.sh
- structorizer.sh
> Updated startscripts

- makeStructorizer
... as it is the case with a fresh checkout
> create bin directory, if missing

- makeStructorizer
Menu was broken, see #595, also Executor and Turtleizer
> added missing ressources

- src/lu/fisch/structorizer/parsers/AuParser.java
- src/lu/fisch/structorizer/parsers/ParserTemplate.pgt
- src/lu/fisch/structorizer/parsers/StructorizerParserTemplate.pgt
I found those in an old checkout and wanted to upload them before deletion.
@codemanyak We may have talked about all or some of those before. Can you please check if any of these changes are useful (there's no pressure to do this any time soon; the changes are at least one year old...)?
> Parser adjustments - please check if useful

- src/lu/fisch/structorizer/parsers/AuParser.java
- src/lu/fisch/structorizer/parsers/ParserTemplate.pgt
- src/lu/fisch/structorizer/parsers/StructorizerParserTemplate.pgt
Reverts fesch/Structorizer.Desktop#609
> Revert "Parser adjustments - please check if useful"

- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/Menu.java
- src/lu/fisch/structorizer/parsers/CodeParser.java
> Missing CodeParser.java changes -> version 3.29-12

- src/lu/fisch/structorizer/generators/COBOLGenerator.java
- src/lu/fisch/structorizer/generators/Generator.java
- src/lu/fisch/structorizer/gui/Diagram.java
> Code incompatibilities with bugfix branch fixed

- src/lu/fisch/structorizer/gui/CaseEditHelper.java
> Missing class CaseEditHelper.java checked in.

- src/lu/fisch/structorizer/parsers/JavaParser.java
> UTF-BOM character removed.

- src/lu/fisch/structorizer/generators/ArmGenerator.java
Newest (conflicting) changes by A. Simonetta
> ARM Translator

- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/elements/Root.java
- src/lu/fisch/structorizer/elements/Try.java
- src/lu/fisch/structorizer/executor/Executor.java
- src/lu/fisch/structorizer/generators/BASHGenerator.java
- src/lu/fisch/structorizer/generators/BasGenerator.java
- src/lu/fisch/structorizer/generators/PHPGenerator.java
- src/lu/fisch/structorizer/generators/PasGenerator.java
- src/lu/fisch/structorizer/generators/PythonGenerator.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/parsers/CPreParser.java
- src/lu/fisch/structorizer/parsers/JavaParser.java
- src/lu/fisch/structorizer/parsers/ProcessingParser.java
- Error messages for string comparison conversion in Executor now show more precise context.
- #1108
- #1109
- #1110
- #1112
> Version 3.32.14 candidate

- src/lu/fisch/structorizer/elements/Case.java
- src/lu/fisch/structorizer/elements/Element.java
- src/lu/fisch/structorizer/elements/Parallel.java
- src/lu/fisch/structorizer/generators/ArmLineParser.java
- src/lu/fisch/structorizer/generators/CGenerator.java
- src/lu/fisch/structorizer/gui/About.java
- src/lu/fisch/structorizer/gui/Diagram.java
- src/lu/fisch/structorizer/gui/Mainform.java
- src/lu/fisch/structorizer/gui/Menu.java
- src/lu/fisch/structorizer/gui/changelog.txt
- src/lu/fisch/structorizer/gui/parsers.xml
- src/lu/fisch/structorizer/locales/de.txt
- src/lu/fisch/structorizer/locales/en.txt
- src/lu/fisch/structorizer/locales/es.txt
- src/lu/fisch/structorizer/parsers/C99Parser.java
- src/lu/fisch/structorizer/parsers/CPreParser.java
- src/lu/fisch/utils/StringList.java
Seems I won't have the time to integrate more changes before Christmas. so we might publish the fixes gathered by now:
- #1114
- #1115
- #1117
- #311: Preference category renamed ("Diagram" -> "View") according to menu changes, "copy PNG image" and "copy EMF image" moved to menu "Diagram"
- #1116
- #1118
- #1119
> Version 3.32-15 candidate
